export const LAST_UPDATED = "更新 1月30日 00:00"
export const METER_PX = 25;

export const MIN_STAGE_DIMENSION = 3;
export const MAX_STAGE_DIMENSION = 500;

export const MIN_STAGE_MARGIN = 2;
export const MAX_STAGE_MARGIN = 20;

export enum CUSTOM_EVENT {
}

export const ICON = {
  addBlack: "icons/add_black.svg",
  alignHorizontalCenterBlack: "icons/align_horizontal_center_black.svg",
  alignHorizontalLeftBlack: "icons/align_horizontal_left_black.svg",
  alignHorizontalRightBlack: "icons/align_horizontal_right_black.svg",
  alignVerticalBottomBlack: "icons/align_vertical_bottom_black.svg",
  alignVerticalCenterBlack: "icons/align_vertical_center_black.svg",
  alignVerticalTopBlack: "icons/align_vertical_top_black.svg",
  arrowMenuCloseBlack: "icons/arrow_menu_close_black.svg",
  arrowLeftAltBlack: "icons/arrow_left_alt_black.svg",
  arrowMenuOpenBlack: "icons/arrow_menu_open_black.svg",
  arrowRangeBlack: "icons/arrow_range_black.svg",
  arrowRightAltBlack: "icons/arrow_right_alt_black.svg",
  categoryBlack: "icons/category_black.svg",
  checkBlack: "icons/check_black.svg",
  checkWhite: "icons/check_white.svg",
  chevronBackwardBlack: "icons/chevron_backward_black.svg",
  chevronForwardBlack: "icons/chevron_forward_black.svg",
  chevronForwardWhite: "icons/chevron_forward_white.svg",
  clearBlack: "icons/clear_black.svg",
  clear: "icons/clear.svg",
  colorsBlack: "icons/colors_black.svg",
  contentCopyBlack: "icons/content_copy_black.svg",
  contentPasteBlack: "icons/content_paste_black.svg",
  curtainsBlack: "icons/curtains_black.svg",
  deleteBlack: "icons/delete_black.svg",
  downloadBlack: "icons/download_black.svg",
  edit: "icons/edit.svg",
  editBlack: "icons/edit_black.svg",
  editOffBlack: "icons/edit_off_black.svg",
  editDocument: "icons/edit_document.svg",
  expandLessBlack: "icons/expand_less_black.svg",
  expandMoreBlack: "icons/expand_more_black.svg",
  familiarFaceAndZoneBlack: "icons/familiar_face_and_zone_black.svg",
  festival: "icons/festival.svg",
  festivalBlack: "icons/festival_black.svg",
  flagBlack: "icons/flag_black.svg",
  fileExportBlack: "icons/file_export_black.svg",
  fileCopy: "icons/file_copy_black.svg",
  fileSave: "icons/file_save.svg",
  fileSaveBlack: "icons/file_save_black.svg",
  footprintBlack: "icons/footprint_black.svg",
  formatAlignCenterBlack: "icons/format_align_center_black.svg",
  formatAlignLeftBlack: "icons/format_align_left_black.svg",
  formatAlignRightBlack: "icons/format_align_right_black.svg",
  formatBoldBlack: "icons/format_bold_black.svg",
  groups2Black: "icons/groups_2_black.svg",
  heightBlack: "icons/height_black.svg",
  help: "icons/help.svg",
  helpBlack: "icons/help_black.svg",
  horizontalDistributeBlack: "icons/horizontal_distribute_black.svg",
  horizontalRuleBlack: "icons/horizontal_rule_black.svg",
  leftClickBlack: "icons/left_click_black.svg",
  lineCurveBlack: "icons/line_curve_black.svg",
  lineEndArrowNotchBlack: "icons/line_end_arrow_notch_black.svg",
  lineEndBlack: "icons/line_end_black.svg",
  lineStartArrowNotchBlack: "icons/line_start_arrow_notch_black.svg",
  lineStartBlack: "icons/line_start_black.svg",
  listsBlack: "icons/lists_black.svg",
  lockBlack: "icons/lock_black.svg",
  lockOpenBlack: "icons/lock_open_black.svg",
  musicNoteBlack: "icons/music_note_black.svg",
  noteStackBlack: "icons/note_stack_black.svg",
  "personBlack": "icons/person_black.svg",
  "personAddBlack": "icons/person_add_black.svg",
  redoBlack: "icons/redo_black.svg",
  saveBlack: "icons/save_black.svg",
  selectAllBlack: "icons/select_all_black.svg",
  settingsWhite: "icons/settings_white.svg",
  settingsBlack: "icons/settings_black.svg",
  settings: "icons/settings.svg",
  straightenBlack: "icons/straighten_black.svg",
  sortByAlphaBlack: "icons/sort_by_alpha_black.svg",
  speakerNotesBlack: "icons/speaker_notes_black.svg",
  speakerNotesOffBlack: "icons/speaker_notes_off_black.svg",
  stylusNoteBlack: "icons/stylus_note_black.svg",
  swapHorizBlack: "icons/swap_horiz_black.svg",
  switchAccessShortcut: "icons/switch_access_shortcut_black.svg",
  textFieldsAltBlack: "icons/text_fields_alt_black.svg",
  turnRightBlack: "icons/turn_right_black.svg",
  undoBlack: "icons/undo_black.svg",
  uploadBlack: "icons/upload_black.svg",
  verticalDistributeBlack: "icons/vertical_distribute_black.svg",
  visibility: "icons/visibility.svg",
  visibilityBlack: "icons/visibility_black.svg",
  zoomInBlack: "icons/zoom_in_black.svg",
  zoomOutBlack: "icons/zoom_out_black.svg",
}

export const DB_NAME = "MatsuriTairetsuDb";